ip_forward: true
network_compression_threshold: 256
stats: [hidden]
groups:
  ChewLeKitten:
  - admin
servers:
  SMP:
    motd: '&1Just another BungeeCord - Forced Host'
    address: [hidden]
    restricted: false
  Cubed:
    motd: MEMED
    address: [hidden]
    restricted: false
  PVP:
    motd: Being boring since 1982.
    address: [hidden]
    restricted: false
  Minigame:
    motd: whitelisted minigames
    address: [hidden]
    restricted: false
  DontDie:
    motd: whitelisted death
    address: [hidden]
    restricted: false
timeout: 30000
player_limit: 100
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  priorities:
  - SMP
  - Cubed
  - PVP
  - Minigame
  - DontDie
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: [hidden]
  forced_hosts:
    cubed.chew.pw: Cubed
    smp.chew.pw: SMP
    pvp.chew.pw: PVP
    minigame.chew.pw: Minigame
    dontdie.chew.pw: DontDie
  max_players: 100
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
prevent_proxy_connections: false
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - deluxechat.bungee.chat
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.find
  - bungeecord.command.send
  - serverlistplus.admin
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
